'use strict';
const {DatabaseSync}=require('node:sqlite');
const fs=require('fs'),path=require('path'),crypto=require('crypto');
const ROOT=__dirname,DIR=path.join(ROOT,'database'),FILE=path.join(DIR,'voter-awareness.db');
fs.mkdirSync(DIR,{recursive:true});
const db=new DatabaseSync(FILE);db.exec('PRAGMA foreign_keys=ON; PRAGMA journal_mode=WAL; PRAGMA busy_timeout=5000;');
db.exec(`
CREATE TABLE IF NOT EXISTS admins(id INTEGER PRIMARY KEY,username TEXT NOT NULL UNIQUE,email TEXT UNIQUE,password_hash TEXT NOT NULL,created_at TEXT NOT NULL,updated_at TEXT NOT NULL,last_login_at TEXT);
CREATE TABLE IF NOT EXISTS participants(id INTEGER PRIMARY KEY,identifier_hash TEXT NOT NULL UNIQUE,identifier_mask TEXT NOT NULL,registered_at TEXT NOT NULL,last_activity_at TEXT NOT NULL,awareness_started_at TEXT,awareness_completed_at TEXT,status TEXT NOT NULL DEFAULT 'IN_PROGRESS',visits INTEGER NOT NULL DEFAULT 1);
CREATE INDEX IF NOT EXISTS idx_participants_registered ON participants(registered_at);CREATE INDEX IF NOT EXISTS idx_participants_activity ON participants(last_activity_at);CREATE INDEX IF NOT EXISTS idx_participants_status ON participants(status);
CREATE TABLE IF NOT EXISTS awareness_progress(participant_id INTEGER PRIMARY KEY REFERENCES participants(id) ON DELETE CASCADE,general_knowledge_started_at TEXT,general_knowledge_completed_at TEXT,survey_started_at TEXT,survey_completed_at TEXT,game_started_at TEXT,game_completed_at TEXT,quiz_started_at TEXT,quiz_completed_at TEXT,updated_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS survey_responses(id INTEGER PRIMARY KEY,participant_id INTEGER NOT NULL REFERENCES participants(id) ON DELETE CASCADE,survey_key TEXT NOT NULL,question_key TEXT NOT NULL,answer_value TEXT NOT NULL,submitted_at TEXT NOT NULL,UNIQUE(participant_id,survey_key,question_key));
CREATE INDEX IF NOT EXISTS idx_survey_submitted ON survey_responses(submitted_at);
CREATE TABLE IF NOT EXISTS game_progress(participant_id INTEGER PRIMARY KEY REFERENCES participants(id) ON DELETE CASCADE,started_at TEXT,stage_1_at TEXT,stage_2_at TEXT,stage_3_at TEXT,stage_4_at TEXT,stage_5_at TEXT,completed_at TEXT,updated_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS quiz_attempts(id INTEGER PRIMARY KEY,participant_id INTEGER NOT NULL REFERENCES participants(id) ON DELETE CASCADE,answers_json TEXT NOT NULL,score INTEGER NOT NULL,total INTEGER NOT NULL,started_at TEXT NOT NULL,completed_at TEXT NOT NULL);
CREATE INDEX IF NOT EXISTS idx_quiz_participant ON quiz_attempts(participant_id);CREATE INDEX IF NOT EXISTS idx_quiz_completed ON quiz_attempts(completed_at);
CREATE TABLE IF NOT EXISTS activity_logs(id INTEGER PRIMARY KEY,participant_id INTEGER REFERENCES participants(id) ON DELETE SET NULL,event_type TEXT NOT NULL,event_key TEXT NOT NULL,details_json TEXT,created_at TEXT NOT NULL,UNIQUE(participant_id,event_key));
CREATE INDEX IF NOT EXISTS idx_activity_created ON activity_logs(created_at);CREATE INDEX IF NOT EXISTS idx_activity_type ON activity_logs(event_type);
CREATE TABLE IF NOT EXISTS system_settings(setting_key TEXT PRIMARY KEY,setting_value TEXT NOT NULL,updated_at TEXT NOT NULL);
`);
const now=()=>new Date().toISOString();
function passwordHash(password,salt=crypto.randomBytes(16).toString('hex')){return salt+':'+crypto.scryptSync(password,salt,64).toString('hex')}
function verifyPassword(password,stored){const [salt,hash]=String(stored).split(':');if(!salt||!hash)return false;const actual=crypto.scryptSync(password,salt,64);const expected=Buffer.from(hash,'hex');return actual.length===expected.length&&crypto.timingSafeEqual(actual,expected)}
if(!db.prepare('SELECT id FROM admins LIMIT 1').get()){const t=now(),password=process.env.ADMIN_PASSWORD||'ChangeMe!2026';db.prepare('INSERT INTO admins(username,email,password_hash,created_at,updated_at) VALUES(?,?,?,?,?)').run(process.env.ADMIN_USERNAME||'admin',process.env.ADMIN_EMAIL||'admin@localhost',passwordHash(password),t,t)}
function setting(key){return db.prepare('SELECT setting_value value FROM system_settings WHERE setting_key=?').get(key)?.value}
if(!setting('json_migrated')){const file=path.join(ROOT,'data','participants.json');if(fs.existsSync(file)){const old=JSON.parse(fs.readFileSync(file,'utf8'));const insert=db.prepare('INSERT OR IGNORE INTO participants(identifier_hash,identifier_mask,registered_at,last_activity_at,status,visits,awareness_started_at,awareness_completed_at) VALUES(?,?,?,?,?,?,?,?)');const prog=db.prepare('INSERT OR IGNORE INTO awareness_progress(participant_id,general_knowledge_completed_at,game_completed_at,quiz_completed_at,updated_at) VALUES(?,?,?,?,?)');const game=db.prepare('INSERT OR IGNORE INTO game_progress(participant_id,started_at,stage_1_at,stage_2_at,stage_3_at,stage_4_at,stage_5_at,completed_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?)');const quiz=db.prepare('INSERT INTO quiz_attempts(participant_id,answers_json,score,total,started_at,completed_at) VALUES(?,?,?,?,?,?)');for(const [hash,p] of Object.entries(old.participants||{})){const done=p.progress?.learned&&p.progress?.gameCompleted&&p.progress?.quizCompleted;insert.run(hash,'legacy-*****',p.createdAt,p.lastSeenAt,done?'COMPLETED':'IN_PROGRESS',p.visits||1,p.createdAt,done?p.lastSeenAt:null);const row=db.prepare('SELECT id FROM participants WHERE identifier_hash=?').get(hash);prog.run(row.id,p.progress?.learned?p.lastSeenAt:null,p.progress?.gameCompleted?p.lastSeenAt:null,p.progress?.quizCompleted?p.lastSeenAt:null,p.lastSeenAt);if(p.progress?.gameCompleted)game.run(row.id,p.lastSeenAt,p.lastSeenAt,p.lastSeenAt,p.lastSeenAt,p.lastSeenAt,p.lastSeenAt,p.lastSeenAt,p.lastSeenAt);if(p.progress?.quizCompleted)quiz.run(row.id,'[]',p.progress.quizScore||0,p.progress.quizTotal||5,p.lastSeenAt,p.lastSeenAt)}}db.prepare('INSERT OR REPLACE INTO system_settings VALUES(?,?,?)').run('json_migrated','1',now())}
function log(participantId,type,key,details=null,at=now()){db.prepare('INSERT OR IGNORE INTO activity_logs(participant_id,event_type,event_key,details_json,created_at) VALUES(?,?,?,?,?)').run(participantId,type,key,details?JSON.stringify(details):null,at);if(participantId)db.prepare('UPDATE participants SET last_activity_at=? WHERE id=?').run(at,participantId)}
function participantProgress(id){const p=db.prepare(`SELECT p.*,a.*,g.stage_1_at,g.stage_2_at,g.stage_3_at,g.stage_4_at,g.stage_5_at,g.completed_at game_done,(SELECT score FROM quiz_attempts q WHERE q.participant_id=p.id ORDER BY q.id DESC LIMIT 1) quiz_score,(SELECT total FROM quiz_attempts q WHERE q.participant_id=p.id ORDER BY q.id DESC LIMIT 1) quiz_total FROM participants p LEFT JOIN awareness_progress a ON a.participant_id=p.id LEFT JOIN game_progress g ON g.participant_id=p.id WHERE p.id=?`).get(id);return p}
function completeIfReady(id){const p=participantProgress(id);if(p.general_knowledge_completed_at&&p.game_completed_at&&p.quiz_completed_at&&!p.awareness_completed_at){const t=now();db.prepare("UPDATE participants SET awareness_completed_at=?,status='COMPLETED',last_activity_at=? WHERE id=?").run(t,t,id);log(id,'AWARENESS_COMPLETED','AWARENESS_COMPLETED',null,t)}}
module.exports={db,now,passwordHash,verifyPassword,log,participantProgress,completeIfReady,FILE};
