'use strict';
const http=require('http'),fs=require('fs'),path=require('path'),crypto=require('crypto');
const {db,now,verifyPassword,log,participantProgress,completeIfReady,FILE:DB_FILE}=require('./database');
const ROOT=__dirname,PORT=Number(process.env.PORT)||3000,publicSessions=new Map(),adminSessions=new Map(),loginAttempts=new Map();
const types={'.html':'text/html; charset=utf-8','.css':'text/css; charset=utf-8','.js':'text/javascript; charset=utf-8','.png':'image/png','.svg':'image/svg+xml'};
function json(res,status,data,extra={}){res.writeHead(status,{'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store',...extra});res.end(JSON.stringify(data))}
function body(req){return new Promise((resolve,reject)=>{let raw='';req.on('data',c=>{raw+=c;if(raw.length>100000)reject(new Error('Request too large'))});req.on('end',()=>{try{resolve(raw?JSON.parse(raw):{})}catch{reject(new Error('Invalid request'))}})})}
function cookies(req){return Object.fromEntries((req.headers.cookie||'').split(';').map(x=>x.trim().split('=').map(decodeURIComponent)).filter(x=>x.length===2))}
function hashId(id){return crypto.createHash('sha256').update('voter-awareness:'+id).digest('hex')}
function maskId(id){return id.length>8?id.slice(0,5)+'-*****-'+id.slice(-1):'***'+id.slice(-2)}
function participant(req){const token=(req.headers.authorization||'').replace(/^Bearer\s+/i,'');const id=publicSessions.get(token);return id?{id,token}:null}
function publicProgress(id,returning=false){const p=participantProgress(id);return {returning,progress:{registered:true,learned:!!p.general_knowledge_completed_at,gameCompleted:!!p.game_completed_at,quizCompleted:!!p.quiz_completed_at,quizScore:p.quiz_score??null,quizTotal:p.quiz_total??null}}}
function admin(req){const sid=cookies(req).admin_session,s=adminSessions.get(sid);if(!s||s.expires<Date.now()){if(sid)adminSessions.delete(sid);return null}s.expires=Date.now()+30*60*1000;return s}
function requireAdmin(req,res,mutating=false){const s=admin(req);if(!s){json(res,401,{error:'Admin authentication required.'});return null}if(mutating&&req.headers['x-csrf-token']!==s.csrf){json(res,403,{error:'Invalid security token.'});return null}return s}
function count(sql,...params){return Number(db.prepare(sql).get(...params)?.n||0)}
async function publicApi(req,res,url){
 if(req.method==='POST'&&url.pathname==='/api/register'){const data=await body(req),cnic=String(data.cnic||'').replace(/\D/g,'');if(cnic.length<5||cnic.length>13)return json(res,400,{error:'Enter a valid CAC / CNIC number.'});const hash=hashId(cnic),t=now();let p=db.prepare('SELECT * FROM participants WHERE identifier_hash=?').get(hash),returning=!!p;if(!p){const out=db.prepare('INSERT INTO participants(identifier_hash,identifier_mask,registered_at,last_activity_at,awareness_started_at,status) VALUES(?,?,?,?,?,?)').run(hash,maskId(cnic),t,t,t,'IN_PROGRESS');p={id:Number(out.lastInsertRowid)};db.prepare('INSERT INTO awareness_progress(participant_id,updated_at) VALUES(?,?)').run(p.id,t);db.prepare('INSERT INTO game_progress(participant_id,updated_at) VALUES(?,?)').run(p.id,t);log(p.id,'REGISTERED','REGISTERED',null,t)}else db.prepare('UPDATE participants SET visits=visits+1,last_activity_at=? WHERE id=?').run(t,p.id);const token=crypto.randomBytes(24).toString('hex');publicSessions.set(token,p.id);return json(res,200,{token,participant:publicProgress(p.id,returning)})}
 const found=participant(req);if(!found)return json(res,401,{error:'Your session has ended. Enter your CAC / CNIC again.'});const id=found.id,t=now();
 if(req.method==='GET'&&url.pathname==='/api/progress')return json(res,200,{participant:publicProgress(id).progress?publicProgress(id):null});
 if(req.method==='POST'&&url.pathname==='/api/activity'){const data=await body(req),allowed=new Set(['GENERAL_KNOWLEDGE_STARTED','SURVEY_STARTED','SURVEY_COMPLETED','GAME_STARTED','QUIZ_STARTED']),type=String(data.type||'');if(!allowed.has(type))return json(res,400,{error:'Invalid activity.'});const map={GENERAL_KNOWLEDGE_STARTED:'general_knowledge_started_at',SURVEY_STARTED:'survey_started_at',SURVEY_COMPLETED:'survey_completed_at',GAME_STARTED:'game_started_at',QUIZ_STARTED:'quiz_started_at'},col=map[type];db.prepare(`UPDATE awareness_progress SET ${col}=COALESCE(${col},?),updated_at=? WHERE participant_id=?`).run(t,t,id);if(type==='GAME_STARTED')db.prepare('UPDATE game_progress SET started_at=COALESCE(started_at,?),updated_at=? WHERE participant_id=?').run(t,t,id);log(id,type,type);return json(res,200,{ok:true})}
 if(req.method==='POST'&&url.pathname==='/api/progress/learn'){db.prepare('UPDATE awareness_progress SET general_knowledge_started_at=COALESCE(general_knowledge_started_at,?),general_knowledge_completed_at=COALESCE(general_knowledge_completed_at,?),updated_at=? WHERE participant_id=?').run(t,t,t,id);log(id,'GENERAL_KNOWLEDGE_COMPLETED','GENERAL_KNOWLEDGE_COMPLETED');completeIfReady(id);return json(res,200,{progress:publicProgress(id).progress})}
 if(req.method==='POST'&&url.pathname==='/api/progress/game-stage'){const data=await body(req),stage=Number(data.stage);if(!Number.isInteger(stage)||stage<1||stage>5)return json(res,400,{error:'Invalid game stage.'});const g=db.prepare('SELECT * FROM game_progress WHERE participant_id=?').get(id);if(stage>1&&!g['stage_'+(stage-1)+'_at'])return json(res,409,{error:'Complete checkpoints in order.'});db.prepare(`UPDATE game_progress SET started_at=COALESCE(started_at,?),stage_${stage}_at=COALESCE(stage_${stage}_at,?),updated_at=? WHERE participant_id=?`).run(t,t,t,id);db.prepare('UPDATE awareness_progress SET game_started_at=COALESCE(game_started_at,?),updated_at=? WHERE participant_id=?').run(t,t,id);log(id,'GAME_STAGE_'+stage+'_COMPLETED','GAME_STAGE_'+stage+'_COMPLETED');return json(res,200,{ok:true})}
 if(req.method==='POST'&&url.pathname==='/api/progress/game'){const g=db.prepare('SELECT stage_5_at FROM game_progress WHERE participant_id=?').get(id);if(!g?.stage_5_at)return json(res,409,{error:'Reach all five checkpoints first.'});db.prepare('UPDATE game_progress SET completed_at=COALESCE(completed_at,?),updated_at=? WHERE participant_id=?').run(t,t,id);db.prepare('UPDATE awareness_progress SET game_started_at=COALESCE(game_started_at,?),game_completed_at=COALESCE(game_completed_at,?),updated_at=? WHERE participant_id=?').run(t,t,t,id);log(id,'GAME_COMPLETED','GAME_COMPLETED');completeIfReady(id);return json(res,200,{progress:publicProgress(id).progress})}
 if(req.method==='POST'&&url.pathname==='/api/quiz/submit'){const data=await body(req),answers=data.answers,correct=[1,0,1,0,1];if(!Array.isArray(answers)||answers.length!==5||answers.some(x=>!Number.isInteger(x)||x<0||x>2))return json(res,400,{error:'Answer every question before submitting.'});const score=answers.reduce((n,a,i)=>n+(a===correct[i]),0);db.prepare('INSERT INTO quiz_attempts(participant_id,answers_json,score,total,started_at,completed_at) VALUES(?,?,?,?,?,?)').run(id,JSON.stringify(answers),score,5,t,t);db.prepare('UPDATE awareness_progress SET quiz_started_at=COALESCE(quiz_started_at,?),quiz_completed_at=?,updated_at=? WHERE participant_id=?').run(t,t,t,id);log(id,'QUIZ_COMPLETED','QUIZ_COMPLETED',{score,total:5});completeIfReady(id);return json(res,200,{score,total:5,complete:true})}
 return json(res,404,{error:'Not found'});
}
async function adminApi(req,res,url){
 if(req.method==='POST'&&url.pathname==='/api/admin/login'){const ip=req.socket.remoteAddress||'local',a=loginAttempts.get(ip)||{n:0,until:0};if(a.until>Date.now())return json(res,429,{error:'Too many attempts. Try again later.'});const data=await body(req),user=db.prepare('SELECT * FROM admins WHERE username=? OR email=?').get(String(data.username||''),String(data.username||''));if(!user||!verifyPassword(String(data.password||''),user.password_hash)){a.n++;if(a.n>=5){a.until=Date.now()+5*60*1000;a.n=0}loginAttempts.set(ip,a);return json(res,401,{error:'Invalid username or password.'})}loginAttempts.delete(ip);const sid=crypto.randomBytes(32).toString('hex'),csrf=crypto.randomBytes(24).toString('hex');adminSessions.set(sid,{adminId:user.id,username:user.username,csrf,expires:Date.now()+30*60*1000});db.prepare('UPDATE admins SET last_login_at=? WHERE id=?').run(now(),user.id);return json(res,200,{username:user.username,csrf},{'Set-Cookie':`admin_session=${sid}; HttpOnly; SameSite=Strict; Path=/; Max-Age=1800`})}
 if(req.method==='GET'&&url.pathname==='/api/admin/session'){const s=requireAdmin(req,res);if(!s)return;return json(res,200,{username:s.username,csrf:s.csrf})}
 if(req.method==='POST'&&url.pathname==='/api/admin/logout'){const s=requireAdmin(req,res,true);if(!s)return;adminSessions.delete(cookies(req).admin_session);return json(res,200,{ok:true},{'Set-Cookie':'admin_session=; HttpOnly; SameSite=Strict; Path=/; Max-Age=0'})}
 const s=requireAdmin(req,res);if(!s)return;
 if(req.method==='GET'&&url.pathname==='/api/admin/dashboard'){const total=count('SELECT COUNT(*) n FROM participants'),today=new Date().toISOString().slice(0,10);const k={total,today:count('SELECT COUNT(*) n FROM participants WHERE substr(registered_at,1,10)=?',today),awarenessStarted:count('SELECT COUNT(*) n FROM participants WHERE awareness_started_at IS NOT NULL'),awarenessCompleted:count('SELECT COUNT(*) n FROM participants WHERE awareness_completed_at IS NOT NULL'),surveyCompleted:count('SELECT COUNT(*) n FROM awareness_progress WHERE survey_completed_at IS NOT NULL'),gameStarted:count('SELECT COUNT(*) n FROM awareness_progress WHERE game_started_at IS NOT NULL'),gameCompleted:count('SELECT COUNT(*) n FROM awareness_progress WHERE game_completed_at IS NOT NULL'),quizCompleted:count('SELECT COUNT(*) n FROM awareness_progress WHERE quiz_completed_at IS NOT NULL')};k.averageQuiz=Number(db.prepare('SELECT ROUND(AVG(score*100.0/total),1) n FROM quiz_attempts').get()?.n||0);k.completionRate=total?Math.round(k.awarenessCompleted*1000/total)/10:0;const recent=db.prepare(`SELECT l.event_type,l.details_json,l.created_at,p.identifier_mask FROM activity_logs l LEFT JOIN participants p ON p.id=l.participant_id ORDER BY l.id DESC LIMIT 10`).all();const funnel={registered:total,generalKnowledge:count('SELECT COUNT(*) n FROM awareness_progress WHERE general_knowledge_completed_at IS NOT NULL'),survey:count('SELECT COUNT(*) n FROM awareness_progress WHERE survey_completed_at IS NOT NULL'),game: k.gameCompleted,quiz:k.quizCompleted,completed:k.awarenessCompleted};return json(res,200,{kpis:k,recent,funnel})}
 if(req.method==='GET'&&url.pathname==='/api/admin/participants'){const page=Math.max(1,Number(url.searchParams.get('page'))||1),size=20,search=String(url.searchParams.get('search')||'').slice(0,40),status=String(url.searchParams.get('status')||''),where=[],params=[];if(search){where.push('p.identifier_mask LIKE ?');params.push('%'+search+'%')}if(['IN_PROGRESS','COMPLETED'].includes(status)){where.push('p.status=?');params.push(status)}const w=where.length?'WHERE '+where.join(' AND '):'';const total=count(`SELECT COUNT(*) n FROM participants p ${w}`,...params);const rows=db.prepare(`SELECT p.id,p.identifier_mask,p.registered_at,p.last_activity_at,p.status,a.general_knowledge_completed_at,a.survey_completed_at,a.game_completed_at,a.quiz_completed_at,(SELECT score||'/'||total FROM quiz_attempts q WHERE q.participant_id=p.id ORDER BY id DESC LIMIT 1) quiz_score FROM participants p LEFT JOIN awareness_progress a ON a.participant_id=p.id ${w} ORDER BY p.id DESC LIMIT ? OFFSET ?`).all(...params,size,(page-1)*size);return json(res,200,{rows,total,page,pages:Math.max(1,Math.ceil(total/size))})}
 const detail=url.pathname.match(/^\/api\/admin\/participants\/(\d+)$/);if(req.method==='GET'&&detail){const id=Number(detail[1]),p=participantProgress(id);if(!p)return json(res,404,{error:'Participant not found.'});const activity=db.prepare('SELECT event_type,details_json,created_at FROM activity_logs WHERE participant_id=? ORDER BY id').all(id),attempts=db.prepare('SELECT score,total,completed_at FROM quiz_attempts WHERE participant_id=? ORDER BY id DESC').all(id);return json(res,200,{participant:{id:p.id,identifier:p.identifier_mask,registeredAt:p.registered_at,lastActivity:p.last_activity_at,status:p.status,completedAt:p.awareness_completed_at},progress:p,activity,attempts})}
 if(req.method==='GET'&&url.pathname==='/api/admin/game'){const started=count('SELECT COUNT(*) n FROM game_progress WHERE started_at IS NOT NULL'),completed=count('SELECT COUNT(*) n FROM game_progress WHERE completed_at IS NOT NULL'),stages=[1,2,3,4,5].map(i=>count(`SELECT COUNT(*) n FROM game_progress WHERE stage_${i}_at IS NOT NULL`));return json(res,200,{started,completed,rate:started?Math.round(completed*1000/started)/10:0,stages})}
 if(req.method==='GET'&&url.pathname==='/api/admin/quiz'){const started=count('SELECT COUNT(*) n FROM awareness_progress WHERE quiz_started_at IS NOT NULL'),completed=count('SELECT COUNT(*) n FROM awareness_progress WHERE quiz_completed_at IS NOT NULL'),stats=db.prepare('SELECT ROUND(AVG(score),2) average,MAX(score) highest FROM quiz_attempts').get(),rows=db.prepare('SELECT p.identifier_mask participant,q.score,q.total,q.completed_at FROM quiz_attempts q JOIN participants p ON p.id=q.participant_id ORDER BY q.id DESC LIMIT 100').all();return json(res,200,{started,completed,rate:started?Math.round(completed*1000/started)/10:0,...stats,rows})}
 if(req.method==='GET'&&url.pathname==='/api/admin/survey'){const started=count('SELECT COUNT(*) n FROM awareness_progress WHERE survey_started_at IS NOT NULL'),completed=count('SELECT COUNT(*) n FROM awareness_progress WHERE survey_completed_at IS NOT NULL'),answers=db.prepare('SELECT question_key,answer_value,COUNT(*) count FROM survey_responses GROUP BY question_key,answer_value ORDER BY question_key,count DESC').all();return json(res,200,{started,completed,rate:started?Math.round(completed*1000/started)/10:0,answers})}
 if(req.method==='GET'&&url.pathname==='/api/admin/report'){const from=url.searchParams.get('from')||'0000',to=url.searchParams.get('to')||'9999',data={registrations:count('SELECT COUNT(*) n FROM participants WHERE registered_at BETWEEN ? AND ?',from,to+'T23:59:59.999Z'),surveyCompleted:count('SELECT COUNT(*) n FROM awareness_progress WHERE survey_completed_at BETWEEN ? AND ?',from,to+'T23:59:59.999Z'),gameStarted:count('SELECT COUNT(*) n FROM awareness_progress WHERE game_started_at BETWEEN ? AND ?',from,to+'T23:59:59.999Z'),gameCompleted:count('SELECT COUNT(*) n FROM awareness_progress WHERE game_completed_at BETWEEN ? AND ?',from,to+'T23:59:59.999Z'),quizCompleted:count('SELECT COUNT(*) n FROM awareness_progress WHERE quiz_completed_at BETWEEN ? AND ?',from,to+'T23:59:59.999Z'),awarenessCompleted:count('SELECT COUNT(*) n FROM participants WHERE awareness_completed_at BETWEEN ? AND ?',from,to+'T23:59:59.999Z'),averageQuiz:Number(db.prepare('SELECT ROUND(AVG(score*100.0/total),1) n FROM quiz_attempts WHERE completed_at BETWEEN ? AND ?').get(from,to+'T23:59:59.999Z')?.n||0)};if(url.searchParams.get('format')==='csv'){const csv='Metric,Value\n'+Object.entries(data).map(([k,v])=>`${k},${v}`).join('\n');res.writeHead(200,{'Content-Type':'text/csv','Content-Disposition':'attachment; filename="voter-awareness-report.csv"'});return res.end(csv)}return json(res,200,{from,to,data})}
 return json(res,404,{error:'Not found'});
}
function staticFile(req,res,url){let pathname=url.pathname;if(pathname==='/')pathname='/index.html';if(pathname==='/admin'||pathname.startsWith('/admin/'))pathname='/admin/index.html';const file=path.resolve(ROOT,'.'+decodeURIComponent(pathname));if(!file.startsWith(ROOT+path.sep))return json(res,403,{error:'Forbidden'});fs.stat(file,(err,stat)=>{if(err||!stat.isFile()){res.writeHead(404);return res.end('Not found')}res.writeHead(200,{'Content-Type':types[path.extname(file)]||'application/octet-stream','Cache-Control':path.extname(file)==='.png'?'public, max-age=86400':'no-cache','X-Content-Type-Options':'nosniff','X-Frame-Options':'DENY','Referrer-Policy':'same-origin'});fs.createReadStream(file).pipe(res)})}
const server=http.createServer(async(req,res)=>{const url=new URL(req.url,'http://localhost');try{if(url.pathname.startsWith('/api/admin/'))await adminApi(req,res,url);else if(url.pathname.startsWith('/api/'))await publicApi(req,res,url);else staticFile(req,res,url)}catch(e){console.error(e);if(!res.headersSent)json(res,500,{error:'The service is unavailable. Please try again.'})}});
if(require.main===module)server.listen(PORT,'0.0.0.0',()=>console.log(`Voter Awareness running at http://localhost:${PORT}\nDatabase: ${DB_FILE}`));
module.exports={server,hashId};
